### ISSUE TITLE
Add bits scripts to module

### ISSUE THREAD

**Issue by stephenegriffin** [SheetJS/js-codepage#16]
Right now I'm using sbcs due to its small size. I would like the flexibility to add a few missing scripts via the bits files instead of flipping to the full table. Could we get the bits dir added back to the module to aid in this?

**Comment by SheetJSDev** [comment]
Which DBCS codepages do you need?  If you specifically need the common East Asian codepages, `cpexcel` includes:

- 932 (Shift-JIS)
- 936 (Simplified Chinese)
- 949 (Hangul Korean)
- 950 (Traditional Chinese Big5)

as well as common Windows and Macintosh codepages used by Excel and dBASE.

We're not against adding them back in, just curious.

**Comment by stephenegriffin** [comment]
Right now it's 936. I use codepage.js to handle parsing of RFC 2047 blobs. Right now I only support a handful of character sets, but I'm considering supporting a whole lot more. I could do this by loading the full cptable, but I thought I might save a bunch of bandwidth by loading the more obscure codepages on demand as needed.

**Comment by SheetJSDev** [comment]
1.13.1 (just published) includes the bits.  We didn't bother updating the version in the script since there was no actual content change.  https://unpkg.com/codepage/bits/ lists the individual files now :)
